### PR TITLE
Added PID controller functionality

### PR DESCRIPTION
**Pull request by SamueljWilson**

### CODE REVIEW

**Comment by jasone** [comment]
There are some merge conflicts due to having based your work on a slightly older version than what is currently committed to the main branch. Do you see how to resolve the conflicts using the web editor?

**Review by jasone — APPROVED** [review]
Looks good! There are some techniques for rewriting history once you have a series of changes figured out that can help make changes look as if no twisty turns were taken during development, but let's not worry about that yet.

**Comment by SamueljWilson** [comment]
I resolved the conflicts manually, but for some reason it still says that we cannot rebase and merge because of conflicts, even though it does not list any.

**Comment by jasone** [comment]
Hmm, the commit history is a pretty big mess, because there were four divergent (similar but not identical) commits already on the main branch that you reimplemented. I sat down at a Linux box and created a resolved linear history by rebasing rather than merging. But due to line ending conventions being different between Linux and Windows this was extra messy to do, and my result actually converted the line endings to the Unix convention.

For reference, here's my resolved branch https://github.com/jasone/FlatbotCommand/pull/new/maxSpeed and the associated pull request https://github.com/TeraViks/FlatbotCommand/pull/4 . As you can see, the line ending change makes this version unmergable too, but I think it is correct in every other respect.

I'm out of time to redo the rebase right now. I think there is support for doing the rebase in the GitHub desktop app; you might want to take a look at it and see whether you can make it work. This is unfortunately a rather complicated conflict to deal with on your first attempt.

**Pull request closed without merging**
